language: node_js

node_js:
  - '6.6.0'

notifications:
  email:
    on_failure: change

cache:
  directories:
    - node_modules

before_install:
  - npm install -g angular-cli@latest
  - npm install -g firebase-tools
  - npm install -g firebase-bolt
  - export COMMIT_MESSAGE=\"$(git log --format=%B --no-merges -n 1)\"
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: npm run build

after_success:
  - npm run codecov
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then firebase deploy --message="$COMMIT_MESSAGE" --token=${FIREBASE_TOKEN}; fi'
